export const FETCH_MOVIE_DATA_REQUEST = 'FETCH_MOVIE_DATA_REQUEST'
export const FETCH_MOVIE_DATA_SUCCESS = 'FETCH_MOVIE_DATA_SUCCESS'
export const FETCH_MOVIE_DATA_ERROR = 'FETCH_MOVIE_DATA_ERROR'
export const OPEN_ITEM_MODAL = 'OPEN_ITEM_MODAL'